version: "2.0"
services:
   web:
     build: .
     ports:
       - "5000:5000"
     depends_on:
       - redis
     networks:
       - swarm_network
   redis:
     image: redis
     networks:
       - swarm_network
networks:
    swarm_network:
            external: true